name: X poster every 2.5h

on:
  schedule:
    # Every 5 hours at minute 0: 00:00, 05:00, 10:00, 15:00, 20:00 UTC
    - cron: "0 */5 * * *"
    # Offset series: Every 5 hours starting at hour 2, minute 30:
    # 02:30, 07:30, 12:30, 17:30, 22:30 UTC
    - cron: "30 2-22/5 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: python bot.py
